### ISSUE TITLE
AttributeError: Can't get attribute 'ConvBNReLU' on <module 'torchvision.models.mobilenet'

### ISSUE THREAD

**Issue by HeinAilytics** [erdemunal35/WaterSegNets#1]
AttributeError: Can't get attribute 'ConvBNReLU' on <module 'torchvision.models.mobilenet' from 'F:\\Python\\envs\\waterseg\\lib\\site-packages\\torchvision\\models\\mobilenet.py'>
 Although I have already installed all of the required libraries, got this error when I try to run test.py. Has anyone had this error before?

**Comment by erdemunal35** [comment]
Hi HeinAilytics,
You should use such code to select models: `preprocessing_fn = smp.encoders.get_preprocessing_fn('resnet18', 'imagenet')` 
Also, I am not sure if you can find such a model named 'mobilenet', maybe you should search for mobilenetV2', 'mobilenetV3'
